[project]
name = "sircylclient"
version = "0.1.0"
description = "Cliente de acceso a SirCyL"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "zeep[xmlsec]>=4.3.2",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    {include-group = "lint"},
    {include-group = "test"}
]
lint = [
    "ruff>=0.14.5",
]
prod = [
]
test = [
    "pytest>=9.0.1",
]