[project]
name = "authzclient"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cachetools>=6.2.2",
    "pydantic>=2.12.4",
    "requests>=2.32.5",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    {include-group = "lint"},
    {include-group = "test"}
]
lint = [
    "ruff>=0.14.5",
]
prod = [
]
test = [
    "pytest>=9.0.1",
]

[tool.uv]
default-groups = ["dev", "prod"]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/jcyl-gss-security/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
username = "__token__"
password = "pypi-AgENdGVzdC5weXBpLm9yZwIkOGFhNjU1OTgtODE3NS00OWFhLWI2MTMtMDZiZDYyMjcyMzI1AAIqWzMsIjM2MDQ2MjI4LTk4YzQtNDAzZC1iMjk4LWFkMjQxZTA4N2JmYyJdAAAGIFuJ3bd9_GTyIu9uczS5MeLpM3TgjWCtBRjyQoGktSYg"